{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aiops-triage.apiName" . }}
  labels:
    app.kubernetes.io/component: api
    {{- include "aiops-triage.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "aiops-triage.selectorLabels" . | nindent 6 }}
{{- end }}
