apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops-triage.apiName" . }}
  labels:
    {{- include "aiops-triage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: api
    {{- include "aiops-triage.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
